import { readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  STUDIO_EDITOR,
  STUDIO_NOT_OFFERED,
  STUDIO_PAGE_SECTIONS,
  STUDIO_TEXT_BLOCKS
} from '#shared/utils/studio-editor'

// The palette Studio serves is generated by `nuxt-component-meta` and shifts
// between builds, so nothing except this allowlist decides what the owner is
// offered. These are the checks that keep it honest.
const CONTENT_COMPONENTS_DIR = fileURLToPath(new URL('../../app/components/content', import.meta.url))

const contentComponents = readdirSync(CONTENT_COMPONENTS_DIR)
  .filter(name => name.endsWith('.vue'))
  .map(name => name.replace(/\.vue$/, ''))
  .sort()

const offered: string[] = STUDIO_EDITOR.components?.include ?? []

describe('the studio insert palette', () => {
  it('offers every content component, or names why it does not', () => {
    const undecided = contentComponents.filter(
      name => !offered.includes(name) && !(name in STUDIO_NOT_OFFERED)
    )

    expect(
      undecided,
      'a new content component must either be offered to the owner or listed in STUDIO_NOT_OFFERED with a reason'
    ).toEqual([])
  })

  // The other direction: a rename would otherwise leave an entry in the owner's
  // menu that inserts a tag nothing renders.
  it('offers nothing that is not a content component', () => {
    const dangling = offered.filter(name => !contentComponents.includes(name))

    expect(dangling).toEqual([])
  })

  it('puts every offered block in exactly one group', () => {
    const grouped = (STUDIO_EDITOR.components?.groups ?? []).flatMap(group => group.include)

    expect([...grouped].sort()).toEqual([...offered].sort())
    expect(new Set(grouped).size, 'a block listed in two groups').toBe(grouped.length)
  })

  it('omits anything that reaches the menu ungrouped', () => {
    expect(STUDIO_EDITOR.components?.ungrouped).toBe('omit')
  })

  it('keeps the two groups distinct', () => {
    const textBlocks: string[] = [...STUDIO_TEXT_BLOCKS]
    const overlap = STUDIO_PAGE_SECTIONS.filter(name => textBlocks.includes(name))

    expect(overlap).toEqual([])
  })

  // Every removed block rendered fine; that was never the problem. They are out
  // because a cafe owner should not be choosing between a Card, a Card Group
  // and five ways to display source code.
  it.each([
    'Accordion',
    'AccordionItem',
    'Badge',
    'Card',
    'CardGroup',
    'CodeCollapse',
    'CodeGroup',
    'CodeIcon',
    'CodePreview',
    'CodeTree',
    'Collapsible',
    'Field',
    'FieldGroup',
    'Kbd',
    'Prompt',
    'Steps',
    'Tabs',
    'TabsItem',
    'Note',
    'Tip',
    'Warning',
    'Caution',
    // These take a whole event or dish as a prop, fetched by a query. There is
    // no way to supply one from a markdown body.
    'EventsEventCard',
    'EventsEventFeature',
    'MenuItemCard',
    // Nuxt UI's own internals, which reach the meta list through content usage.
    'UAccordion',
    'UBadge',
    'UCard',
    'UCollapsible',
    'UIcon',
    'UPageCard',
    'UPageFeature',
    'UTabs'
  ])('does not offer %s', (name) => {
    expect(offered).not.toContain(name)
  })

  // Studio's own `CommandKey` union types this list, so a typo is a typecheck
  // failure rather than a command that quietly stays in the toolbar.
  it('drops the commands that have no use on a cafe site', () => {
    expect([...(STUDIO_EDITOR.commands?.exclude ?? [])].sort())
      .toEqual(['code', 'codeBlock', 'heading1', 'video'])
  })

  it('restricts the icon picker to the collections bundled into the client', () => {
    expect(STUDIO_EDITOR.iconLibraries).toEqual(['lucide', 'simple-icons'])
  })
})
